<a href="https://colab.research.google.com/github/carloslesmes/BlogCL/blob/master/py_statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Módulo `statistics`

In [ ]:
import statistics as stats

In [ ]:
dir(statistics)

['Counter',
 'Decimal',
 'Fraction',
 'LinearRegression',
 'NormalDist',
 'StatisticsError',
 '_SQRT2',
 '__all__',
 '__annotations__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_coerce',
 '_convert',
 '_decimal_sqrt_of_frac',
 '_exact_ratio',
 '_fail_neg',
 '_float_sqrt_of_frac',
 '_integer_sqrt_of_frac_rto',
 '_isfinite',
 '_mean_stdev',
 '_normal_dist_inv_cdf',
 '_rank',
 '_sqrt_bit_width',
 '_ss',
 '_sum',
 'bisect_left',
 'bisect_right',
 'correlation',
 'count',
 'covariance',
 'defaultdict',
 'erf',
 'exp',
 'fabs',
 'fmean',
 'fsum',
 'geometric_mean',
 'groupby',
 'harmonic_mean',
 'hypot',
 'itemgetter',
 'linear_regression',
 'log',
 'math',
 'mean',
 'median',
 'median_grouped',
 'median_high',
 'median_low',
 'mode',
 'multimode',
 'namedtuple',
 'numbers',
 'pstdev',
 'pvariance',
 'quantiles',
 'random',
 'reduce',
 'repeat',
 'sqrt',
 'stdev',
 'sumprod',
 'sys',
 'tau',
 'variance']

In [ ]:
datos = [1, 2, 3, 4, 5]

In [ ]:
stats.mean(datos)

3

In [ ]:
stats.median(datos)

3

In [ ]:
stats.stdev(datos)

1.5811388300841898

In [ ]:
stats.variance(datos)

2.5

In [ ]:
datos1=[2,3,5,2,4]

In [ ]:
stats.covariance(datos,datos1)

0.75

## Numpy
Vea [numpy](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [ ]:
%pip install numpy
import numpy as np

In [ ]:
a = np.array([11, 2, 35, 45, 59, 6])
a

array([11,  2, 35, 45, 59,  6])

In [ ]:
a.ndim

1

In [ ]:
a.size

6

In [ ]:
a.shape

(6,)

In [ ]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.shape

(3, 4)

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.sort(a)

array([ 2,  6, 11, 35, 45, 59])

In [ ]:
b < 6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [ ]:
b[b<6]

array([1, 2, 3, 4, 5])

In [ ]:
%pip install scipy
import scipy as sp

Vea [Scipy](https://docs.scipy.org/doc/scipy/tutorial/index.html#user-guide)

In [ ]:
import scipy.stats as stats

In [ ]:
y = stats.expon.rvs(7, size=1000)

In [ ]:
y.min()

np.float64(7.0015182262301705)

In [ ]:
y.max()

np.float64(13.507599785751149)

In [ ]:
y.mean()

np.float64(7.995986053671514)

In [ ]:
y.var()

np.float64(0.926857951058388)

In [ ]:
stats.describe(y)

DescribeResult(nobs=np.int64(1000), minmax=(np.float64(7.0015182262301705), np.float64(13.507599785751149)), mean=np.float64(7.995986053671514), variance=np.float64(0.9277857367951833), skewness=np.float64(1.6416590738783166), kurtosis=np.float64(3.44742271252941))

In [ ]:
stats.gmean(y)

np.float64(7.9438160542211484)

In [ ]:
stats.hmean(y)

np.float64(7.896635130151766)

In [ ]:
stats.moment(y, moment=3)

np.float64(1.46488233304575)

In [ ]:
stats.moment(y, moment=4)

np.float64(5.538759457123344)

In [ ]:
stats.skew(y)

np.float64(1.6416590738783166)

In [ ]:
stats.kurtosis(y)

np.float64(3.44742271252941)

In [ ]:
stats.quantile(y, [0.25, 0.75])

array([7.2739796 , 8.44804525])

In [ ]:
stats.percentileofscore(y, 8)

np.float64(64.2)